site_name: SFAI SDK
site_description: A modern and powerful SDK for SFAI
repo_url: https://github.com/salesforce/sfai-sdk
repo_name: salesforce/sfai-sdk
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.action.edit
    - content.action.view
    - toc.integrate
    - toc.follow
    - header.autohide
    - announce.dismiss
  language: en
  palette:
    # Dark mode - Salesforce inspired
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode - Salesforce inspired
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/api
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600&display=swap

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/salesforce/sfai-sdk
      name: GitHub Repository
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@sfai.com
      name: Contact Support
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter:
      execute: false
      include_source: true
      show_input: true
      no_input: false
      include_requirejs: true
      ignore_h1_titles: false
      kernel_name: python3
      theme: auto
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_signature: false
            show_docstring_returns: true
            show_docstring_other_parameters: true
            merge_init_into_class: false
            show_root_toc_entry: false
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
      fallback_to_empty: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: false
      enable_git_follow: false
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
      permalink_title: Anchor link to this section for reference
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      pygments_style: github-dark
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: salesforce
      repo: sfai-sdk
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# Navigation structure (matches actual docs folder structure)
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/README.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Core Architecture: core-architecture.md
  - API Reference:
    - Overview: api/overview.md
    - Modules: api/modules.md
  - CLI:
    - Overview: cli/overview.md
    - Commands: cli/commands.md
  - Use Cases:
    - Local Deployment: usecases/local-deployment.ipynb
    - Heroku Deployment: usecases/heroku-deployment.ipynb
  - FAQ: faq.md
  - Contributing: contributing.md
  - Changelog: changelog.md
