openapi: 3.0.0
info:
  version: 0.0.0
  title: SFAI template
  description: Some description test
x-sfdc:
  agent:
    topic:
      name: sfai_template
      classificationDescription: testing topic
      scope: Your job is to help test agentforce and mulesoft connection
      instructions:
        - hello
paths:
  /invocation:
    post:
      summary: Invoke endpoint
      description: Invoke external endpoint
      x-sfdc:
        agent:
          action:
            publishAsAgentAction: true
      operationId: invoke
      requestBody:
        required: true
        description: request body description
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              x-sfdc:
                agent:
                  action:
                    isUserInput: true
              properties:
                account_id:
                  type: string
                  description: Unique identifier of the customer
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                additionalProperties: false
                x-sfdc:
                  agent:
                    action:
                      isDisplayable: true
                type: object
                properties:
                  customerId:
                    type: string
                  prediction:
                    type: string
        "400":
          description: Invalid request
        "500":
          description: Internal server error
