replicaCount: 1
image:
  repository: sfai-sdk
  tag: latest
  pullPolicy: Always
env:
  - name: PORT
    value: "8080"

ingress:
  className: alb

service:
  type: NodePort
  port: 80
  targetPort: 8080
