name: Deploy package to PyPI

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade build setuptools wheel setuptools_scm

    - name: Clean build artifacts
      run: rm -rf dist/ build/ *.egg-info

    - name: Build package (wheel only)
      run: python -m build --wheel

    - name: Build source distribution
      run: python -m build --sdist --no-isolation

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        password: ${{ secrets.PYPI_TOKEN }}